var mongoose     = require('mongoose');
var Schema       = mongoose.Schema;

var LibItemSchema   = new Schema({
    provider: String,
    id: String,//A unique identifier for the user, as generated by the service provider.
    name: String,
    previewUrl: String,
    description: String,
    fileUrl: String
});

var LibItem = mongoose.model('libitem', LibItemSchema);

module.exports = {
    findLibItemsUniversal : function(params, callback) {
        console.log("trying to find libItems: " + JSON.stringify(params));
        var res = LibItem.find(params, function(err, x){
            console.log("Lib Items: " + JSON.stringify(x));
            callback(err, x);
        });
    },
    addNewLibItem: function (item, callback){
        console.log("adding new lib item: " + JSON.stringify(item));
        var x = new LibItem();
        for (var key in item) {
            x[key] = item[key];}
        x.save(function (err) {
            if (err)
                console.log('error saving lib item');
            console.log("lib item saved: " + JSON.stringify(x));
            callback(err, x);
        });
    },
    deleteLibItem: function (p, callback){
        console.log("deleting libitem: " + JSON.stringify(p));
        LibItem.findOneAndRemove({"_id": p._id.toObjectId()}).exec();
        callback();
    }
}

