var mongoose     = require('mongoose');
var Schema       = mongoose.Schema;

// http://mongoosejs.com/docs/schematypes.html
var UserSchema   = new Schema({
    provider: String,
    id: String,//A unique identifier for the user, as generated by the service provider.
    displayName: String,
    name: {
        familyName: String,
        givenName: String,
        middleName: String
    },
    emails: [{
        value: String,
        type: String
    }],
    photos: [{
        value: String// The URL of the image.
    }]

});

//module.exports = mongoose.model('User', UserSchema);

var User = mongoose.model('User', UserSchema);

module.exports = {
    findUser: function(params, fn){

    },
    addUser: function(params, done){
        console.log("hey");
        var jsonString = '{"some":"json"}';
        console.log("creating user:" + JSON.stringify(params));
        var user = new User();
        for(var key in params) {
            user[key] = params[key];
        }

        user.save(function(err) {
            if (err)
                console.log('error saving user');
            console.log("user saved: " + JSON.stringify(user));
        });
    }
}